#!/usr/bin/env bash

# This file is part of ELNBuildSync
# Copyright (C) 2023-2026 Stephen Gallagher <sgallagh@redhat.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# SPDX-License-Identifier: 	GPL-3.0-or-later

# Created by argbash-init v2.11.0
# ARG_OPTIONAL_SINGLE([log-level],[],[Log verbosity],[INFO])
# ARG_OPTIONAL_SINGLE([static-config-file],[],[Static configuration file],[/etc/elnbuildsync/elnbuildsync.yaml])
# ARG_OPTIONAL_SINGLE([dynamic-config-file],[],[Dynamic configuration file])
# ARG_OPTIONAL_SINGLE([dynamic-config-url],[],[Dynamic configuration Git URL],[https://github.com/fedora-eln/elnbuildsync-config.git])
# ARG_OPTIONAL_SINGLE([dynamic-config-branch],[],[Dynamic configuration Git branch],[main])
# ARG_OPTIONAL_SINGLE([keytab-principal],[],[Keytab principal],[eln-buildsync@FEDORAPROJECT.ORG])
# ARG_OPTIONAL_SINGLE([keytab-file],[],[Keytab file],[])
# ARG_OPTIONAL_SINGLE([koji-profile],[],[Koji profile],[koji])
# ARG_POSITIONAL_DOUBLEDASH([])
# ARG_POSITIONAL_INF([custom],[Additional arguments to pass to the ELNBuildSync daemon])
# ARG_HELP([],[Run the ELNBuildSync daemon])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_custom=()
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_log_level="INFO"
_arg_static_config_file="/etc/elnbuildsync/elnbuildsync.yaml"
_arg_dynamic_config_file=
_arg_dynamic_config_url="https://github.com/fedora-eln/elnbuildsync-config.git"
_arg_dynamic_config_branch="main"
_arg_keytab_principal="eln-buildsync@FEDORAPROJECT.ORG"
_arg_keytab_file=
_arg_koji_profile="koji"


print_help()
{
	printf 'Usage: %s [--log-level <arg>] [--static-config-file <arg>] [--dynamic-config-file <arg>] [--dynamic-config-url <arg>] [--dynamic-config-branch <arg>] [--keytab-principal <arg>] [--keytab-file <arg>] [--koji-profile <arg>] [-h|--help] [--] [<custom-1>] ... [<custom-n>] ...\n' "$0"
	printf '\t%s\n' "<custom>: Additional arguments to pass to the ELNBuildSync daemon"
	printf '\t%s\n' "--log-level: Log verbosity (default: 'INFO')"
	printf '\t%s\n' "--static-config-file: Static configuration file (default: '/etc/elnbuildsync/elnbuildsync.yaml')"
	printf '\t%s\n' "--dynamic-config-file: Dynamic configuration file (no default)"
	printf '\t%s\n' "--dynamic-config-url: Dynamic configuration Git URL (default: 'https://github.com/fedora-eln/elnbuildsync-config.git')"
	printf '\t%s\n' "--dynamic-config-branch: Dynamic configuration Git branch (default: 'main')"
	printf '\t%s\n' "--keytab-principal: Keytab principal (default: 'eln-buildsync@FEDORAPROJECT.ORG')"
	printf '\t%s\n' "--keytab-file: Keytab file (no default)"
	printf '\t%s\n' "--koji-profile: Koji profile (default: 'koji')"
	printf '\t%s\n' "-h, --help: Prints help"
	printf '\n%s\n' "Run the ELNBuildSync daemon"
}


parse_commandline()
{
	_positionals_count=0
	local _key
	while test $# -gt 0
	do
		_key="$1"
		if test "$_key" = '--'
		then
			shift
			test $# -gt 0 || break
			_positionals+=("$@")
			_positionals_count=$((_positionals_count + $#))
			shift $(($# - 1))
			_last_positional="$1"
			break
		fi
		case "$_key" in
			--log-level)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_log_level="$2"
				shift
				;;
			--log-level=*)
				_arg_log_level="${_key##--log-level=}"
				;;
			--static-config-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_static_config_file="$2"
				shift
				;;
			--static-config-file=*)
				_arg_static_config_file="${_key##--static-config-file=}"
				;;
			--dynamic-config-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_dynamic_config_file="$2"
				shift
				;;
			--dynamic-config-file=*)
				_arg_dynamic_config_file="${_key##--dynamic-config-file=}"
				;;
			--dynamic-config-url)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_dynamic_config_url="$2"
				shift
				;;
			--dynamic-config-url=*)
				_arg_dynamic_config_url="${_key##--dynamic-config-url=}"
				;;
			--dynamic-config-branch)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_dynamic_config_branch="$2"
				shift
				;;
			--dynamic-config-branch=*)
				_arg_dynamic_config_branch="${_key##--dynamic-config-branch=}"
				;;
			--keytab-principal)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_keytab_principal="$2"
				shift
				;;
			--keytab-principal=*)
				_arg_keytab_principal="${_key##--keytab-principal=}"
				;;
			--keytab-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_keytab_file="$2"
				shift
				;;
			--keytab-file=*)
				_arg_keytab_file="${_key##--keytab-file=}"
				;;
			--koji-profile)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_koji_profile="$2"
				shift
				;;
			--koji-profile=*)
				_arg_koji_profile="${_key##--koji-profile=}"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names=""
	_our_args=$((${#_positionals[@]} - 0))
	for ((ii = 0; ii < _our_args; ii++))
	do
		_positional_names="$_positional_names _arg_custom[$((ii + 0))]"
	done

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

set -eo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export TMPDIR=/var/tmp

if [ -n "${_arg_keytab_file}" ]; then
  # If we have a keytab, use it to get a Kerberos TGT
  # Otherwise, this is probably being run locally for testing and the
  # host KCM configuration will be used (see local_test_daemon.sh).
  export KRB5CCNAME=FILE:${TMPDIR}/tgt

  echo "Getting Kerberos TGT every hour from ${_arg_keytab_file} for ${_arg_keytab_principal}"
  (while true; do kinit -k -t "${_arg_keytab_file}" ${_arg_keytab_principal}; sleep 55m; done) &
fi

# Make sure Kerberos is working by trying to connect to koji
while true; do
  koji -p ${_arg_koji_profile} hello && break || sleep 3
done

STATIC_ARG="--static-config-file /etc/elnbuildsync/elnbuildsync.yaml"
if [ -n "${_arg_static_config_file}" ]; then
  STATIC_ARG="--static-config-file ${_arg_static_config_file}"
fi

if [ -n "${_arg_dynamic_config_file}" ]; then
  echo "Using dynamic config file at ${_arg_dynamic_config_file}"
  DYNAMIC_ARG="--dynamic-config-file ${_arg_dynamic_config_file}"
elif [ -f /etc/elnbuildsync/elnbuildsync_dynamic.yaml ]; then
  # Check if we have mounted a dynamic config file into the container.
  # This is mostly useful for OpenShift Local testing.
  echo "Using dynamic config file at /etc/elnbuildsync/elnbuildsync_dynamic.yaml"
  DYNAMIC_ARG="--dynamic-config-file /etc/elnbuildsync/elnbuildsync_dynamic.yaml"
else
  echo "Using dynamic config URL at ${_arg_dynamic_config_url}#${_arg_dynamic_config_branch}"
  DYNAMIC_ARG="--dynamic-config-url ${_arg_dynamic_config_url}#${_arg_dynamic_config_branch}"
fi

# Check that the DB password file exists
if [ ! -f /etc/elnbuildsync/ebs_db_pw ]; then
  echo "Error: DB password file /etc/elnbuildsync/ebs_db_pw is missing. Mount it with --volume /local/dir:/etc/elnbuildsync:Z"
  exit 1
fi

# Check that the SMTP password file exists
if [ ! -f /etc/elnbuildsync/ebs_smtp_pw ]; then
  echo "Warning: SMTP password file /etc/elnbuildsync/ebs_smtp_pw is missing. If using SMTP, mount it with --volume /local/dir:/etc/elnbuildsync:Z"
else
  SMTP_ARG="--smtp-pw-file /etc/elnbuildsync/ebs_smtp_pw"
fi

echo "EXECUTING klist"
KRB5_TRACE=/dev/stderr klist -A

python3 --version

echo "Activating virtualenv"
virtualenv --system-site-packages ${TMPDIR}/.venv
. ${TMPDIR}/.venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
pip install "${SCRIPT_DIR}"

export FEDORA_MESSAGING_CONF=/etc/fedora-messaging/config.toml

elnbuildsync \
  $STATIC_ARG \
  $DYNAMIC_ARG \
  --log-level ${_arg_log_level} \
  --db-pw-file /etc/elnbuildsync/ebs_db_pw \
  $SMTP_ARG \
  ${_arg_custom[@]}

# ] <-- needed because of Argbash
