[metadata]
name = distrobuildsync
version = 0.1.0

[options]
packages = find_namespace:
include_package_data = True

[options.packages.find]
where = src

[options.package_data]
distrobuildsync =
  README.md

distrobuildsync.templates =
  status.xml

[options.entry_points]
console_scripts =
    distrobuildsync = distrobuildsync:main