#!/usr/bin/env bash

# This file is part of ELNBuildSync
# Copyright (C) 2023-2026 Stephen Gallagher <sgallagh@redhat.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# SPDX-License-Identifier: GPL-3.0-or-later

# Created by argbash-init v2.11.0 (extend with argbash and regenerate when adding options)
# ARG_OPTIONAL_SINGLE([image-tag],[],[Container image tag for build and Helm image.tag],[latest])
# ARG_OPTIONAL_SINGLE([keytab-file],[],[Path to keytab file for Helm secrets.keytab],[])
# ARG_HELP([],[Build with buildah, copy to cluster registry with skopeo, deploy via Helm])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_image_tag="latest"
_arg_keytab_file=


print_help()
{
	printf 'Usage: %s [--image-tag <arg>] [--keytab-file <arg>] [-h|--help]\n' "$0"
	printf '\t%s\n' "--image-tag: Container image tag for build and Helm image.tag (default: 'latest')"
	printf '\t%s\n' "--keytab-file: Path to keytab file for Helm secrets.keytab (no default)"
	printf '\t%s\n' "-h, --help: Prints help"
	printf '\n%s\n' "Build with buildah, copy to cluster registry with skopeo, deploy via Helm"
}


parse_commandline()
{
	local _key
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			--image-tag)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_image_tag="$2"
				shift
				;;
			--image-tag=*)
				_arg_image_tag="${_key##--image-tag=}"
				;;
			--keytab-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_keytab_file="$2"
				shift
				;;
			--keytab-file=*)
				_arg_keytab_file="${_key##--keytab-file=}"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
				;;
		esac
		shift
	done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ_DIR="${SCRIPT_DIR}/.."
VALUES_FILE="${PROJ_DIR}/helm_charts/values.yaml"
CHART_DIR="${PROJ_DIR}/helm_charts"
RELEASE_NAME="eln-ops"

require_command()
{
	local c
	for c in "$@"; do
		command -v "$c" >/dev/null 2>&1 || die "Required command not found in PATH: $c" 1
	done
}

require_command oc buildah skopeo helm yq

image_repo_from_values()
{
	test -r "$VALUES_FILE" || die "Cannot read ${VALUES_FILE}" 1
	yq '.image.repo' "$VALUES_FILE"
}

public_registry_host()
{
	local out
	if out=$(oc registry info --public=true 2>/dev/null); then
		echo "${out}"
		return 0
	fi
	if out=$(oc registry info --public 2>/dev/null); then
		echo "${out}"
		return 0
	fi
	if out=$(oc registry info 2>/dev/null); then
		echo "${out}"
		return 0
	fi
	return 1
}

echo "OpenShift user: $(oc whoami)"
echo "API server: $(oc whoami --show-server)"

IMAGE_REPO=$(image_repo_from_values)
test -n "${IMAGE_REPO}" || die "Could not parse image.repo from ${VALUES_FILE}" 1

IMAGE_PATH="${IMAGE_REPO#*/}"
test -n "${IMAGE_PATH}" || die "Unexpected image.repo format in values (expected host/path): ${IMAGE_REPO}" 1

echo "Logging in to integrated registry..."
oc registry login

PUBLIC_REGISTRY=$(public_registry_host)
test -n "${PUBLIC_REGISTRY}" || die "Could not resolve public registry host (try: oc registry info --public=true)" 1

FULL_PUSH="${PUBLIC_REGISTRY}/${IMAGE_PATH}:${_arg_image_tag}"
LOCAL_TAG="localhost/elnbuildsync:${_arg_image_tag}"

echo "Building image (Dockerfile) as ${LOCAL_TAG}"
buildah bud -f Dockerfile -t "${LOCAL_TAG}" "${PROJ_DIR}"

echo "Copying image to registry with skopeo (${FULL_PUSH})"
skopeo copy \
    --dest-tls-verify=false \
	"containers-storage:${LOCAL_TAG}" \
	"docker://${FULL_PUSH}"

API_SERVER=$(oc whoami --show-server)
CRC_STATIC_CONFIG="${PROJ_DIR}/tests/etc/crc/elnbuildsync.yaml"
CRC_DYNAMIC_CONFIG="${PROJ_DIR}/tests/etc/crc/elnbuildsync_dynamic.yaml"
test -r "${CRC_STATIC_CONFIG}" || die "Cannot read CRC static config: ${CRC_STATIC_CONFIG}" 1
test -r "${CRC_DYNAMIC_CONFIG}" || die "Cannot read CRC dynamic config: ${CRC_DYNAMIC_CONFIG}" 1

HELM_DESC="openshift_test_daemon image.tag=${_arg_image_tag} sidecar_database=true release=${RELEASE_NAME} chart_dir=helm_charts values=helm_charts/values.yaml image.repo_from_values=${IMAGE_REPO} image_push=${FULL_PUSH} api=${API_SERVER} static_config=${CRC_STATIC_CONFIG} dynamic_config=${CRC_DYNAMIC_CONFIG}"
if [ -n "${_arg_keytab_file}" ]; then
	HELM_DESC="${HELM_DESC} keytab_file=${_arg_keytab_file}"
fi

echo "Deploying Helm release ${RELEASE_NAME}"

helm_cmd=(
	helm upgrade --install --cleanup-on-fail "${RELEASE_NAME}" "${CHART_DIR}"
	--set "image.tag=${_arg_image_tag}"
	--values "${CHART_DIR}/values.yaml"
	--set sidecar_database=true
	--set-file secrets.elnbuildsync_static_config_file="${CRC_STATIC_CONFIG}"
	--set-file secrets.elnbuildsync_dynamic_config_file="${CRC_DYNAMIC_CONFIG}"
	--set-file secrets.database_password="${PROJ_DIR}/tests/etc/crc/ebs_db_pw"
	--set-file secrets.smtp_password="${PROJ_DIR}/tests/etc/crc/ebs_smtp_pw"
	--set-file secrets.oidc_client_secret="${PROJ_DIR}/tests/etc/crc/ebs_oidc_client_secret"
	--set-file secrets.fedora_messaging_config="${PROJ_DIR}/tests/fedora-messaging/fedora.toml"
	--set-file secrets.fedora_messaging_cacert="${PROJ_DIR}/tests/fedora-messaging/cacert.pem"
	--set-file secrets.fedora_messaging_client_pem="${PROJ_DIR}/tests/fedora-messaging/fedora-cert.pem"
	--set-file secrets.fedora_messaging_client_key="${PROJ_DIR}/tests/fedora-messaging/fedora-key.pem"
)

if [ -n "${_arg_keytab_file}" ]; then
	test -r "${_arg_keytab_file}" || die "Cannot read keytab file: ${_arg_keytab_file}" 1
	helm_cmd+=(--set-file "secrets.keytab=${_arg_keytab_file}")
fi

if helm upgrade -h 2>&1 | grep -Fq -- '--description'; then
	helm_cmd+=(--description "${HELM_DESC}")
else
	echo "Warning: this Helm build does not support --description; skipping." >&2
fi

"${helm_cmd[@]}"

# ] <-- needed because of Argbash
