apiVersion: v1
kind: Secret
metadata:
  name: ebs-config
  namespace: {{ .Values.oc_namespace }}
  labels:
    app: {{ .Values.app_name }}
data:
  ebs_db_pw: "{{ .Values.secrets.database_password | b64enc }}"
{{- if .Values.secrets.smtp_password }}
  ebs_smtp_pw: '{{ .Values.secrets.smtp_password | default "" | b64enc }}'
{{- end }}
{{- if .Values.secrets.oidc_client_secret }}
  ebs_oidc_client_secret: '{{ .Values.secrets.oidc_client_secret | default "" | b64enc }}'
{{- end }}
{{- if .Values.secrets.elnbuildsync_static_config_file }}
  elnbuildsync.yaml: '{{ .Values.secrets.elnbuildsync_static_config_file | default "" | b64enc }}'
{{- end }}
{{- if .Values.secrets.elnbuildsync_dynamic_config_file }}
  elnbuildsync_dynamic.yaml: '{{ .Values.secrets.elnbuildsync_dynamic_config_file | default "" | b64enc }}'
{{- end }}
type: Opaque
