[stg]

;configuration for koji cli tool

;url of XMLRPC server
server = https://koji.stg.fedoraproject.org/kojihub

;url of web interface
weburl = https://koji.stg.fedoraproject.org/koji

;url of package download site
topurl = https://kojipkgs.stg.fedoraproject.org/

authtype = kerberos

use_fast_upload = yes
